version: "3.7"
services:

  # ecommerce-database
  battleships-db-postgres:
    image: postgres:latest
    container_name: ecommerce-database
    ports:
      - 5432:5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    restart: always